#!/bin/bash
source .env
echo 'Starting CREATE DATABASE TASKS'
sudo -u postgres psql -c "DROP DATABASE IF EXISTS $POSTGRESQL_DATABASE_NAME;"
sudo -u postgres psql -c "DROP USER IF EXISTS $POSTGRESQL_USER;"
sudo -u postgres psql -c "CREATE USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASSWORD'"
sudo -u postgres psql -c "ALTER USER $POSTGRESQL_USER CREATEDB;"
sudo -u postgres psql -c "CREATE DATABASE $POSTGRESQL_DATABASE_NAME WITH ENCODING='UTF8' OWNER=$POSTGRESQL_USER"
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $POSTGRESQL_DATABASE_NAME TO $POSTGRESQL_USER;"
